### ISSUE TITLE
isDUI function bug

### ISSUE THREAD

**Issue by Monge1h** [jonathanpalma/sivar-utils#2]
**Describe the bug**
When the DUI has a 0 as a verifier, the isDUI function returns false.

**To Reproduce**
use isDUI function with a valid DUI that has a 0 as a verifier.

**Comment by jonathanpalma** [comment]
Hey @Monge1h, thanks for taking the time to submit this PR. It looks great, I am just wondering if would it be possible to add some test cases to validate this scenario?

**Comment by jonathanpalma** [comment]
@all-contributors please add @Monge1h for bug
